### PR TITLE
Update dependencies and plugins plus misc formatting (ie line endings)

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by hazendaz** [comment]
@trajano Not sure if this is valid or not.  Travis fails I assume to recent changes.  I cannot get building with tests locally at all as I get 301 redirects on test expecting a 200.  Travis just fails both on mine and PR.  Otherwise I think this is actually good set of changes.

**Comment by trajano** [comment]
Let's try to merge it an see if it works when it is on master.

**Comment by hazendaz** [comment]
@trajano Looks like same 301 redirect error on travis as well now.  I'm going to run a test locally back before my changes but suspect that was already there since I didn't touch the code itself only plugins.

**Comment by trajano** [comment]
No worries I know the issue I just applied the fix directly.  The target URL has "changed" behaviour so I just fixed to match the new behavior.

**Comment by hazendaz** [comment]
Thanks.  I'm past that issue now.  Have other issues with credentials which is consistent with builds from back 11 months so I'll look into that later.  Build is back to green on travis now.

**Pull request merged**
