### PR TITLE
Fixed scm tag

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by trajano** [comment]
Hmm thanks for catching I wonder what happened to the release plugin.

**Comment by hazendaz** [comment]
I've seen this happen before.  I also wonder how.  Hoping to catch it in action next time...


Sent by Outlook for Android





On Sat, Sep 12, 2015 at 10:09 PM -0700, "Archimedes Trajano" <notifications@github.com> wrote:
Hmm thanks for catching I wonder what happened to the release plugin.

---

**Comment by trajano** [comment]
Only on this project or on other projects?

**Comment by hazendaz** [comment]
On other projects.


Sent by Outlook for Android





On Sun, Sep 13, 2015 at 11:31 PM -0700, "Archimedes Trajano" <notifications@github.com> wrote:
Only on this project or on other projects?

---

**Pull request merged**
